const Colors = {
  PRIMARY_BACKGROUND_COLOR: '#fff',
  PRIMARY_COLOR: ' #ea4c89',
  PRIMARY_TEXT_COLOR: '#000',
  SECONDARY_TEXT_COLOR: '#333',
  SECONDARY_BACKGROUND_COLOR: '#f5f5f5',
  SECONDARY_COLOR: '#f5f5f5',
  SECONDARY_BORDER_COLOR: '#e5e5e5',
  PRIMARY_BUTTON_COLOR: '#c4c4c4',
};

export default Colors;
